name: "test"
on: [push]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: 'Install Nextflow'
        uses: stracquadaniolab/gh-action-setup-nextflow@v23.04.2
        
      - name: 'Stub testing Nextflow pipeline with test profile'
        run: |
          chmod +x bin/*
          nextflow run . -profile github,test -stub

